### ISSUE TITLE
Make the project buildable without tinkering

### ISSUE THREAD

**Issue by attilavs2** [mibi88/MibiCraft#1] opened 2024-07-03 12:28 UTC
Currently the project requires at least adding in the stb perlin header and changing the std to C99 to be able to build.
It is also unbuildable on Debian-based due to a mix of poor packaging of freeglut and incompetence of meson

**Comment by mibi88** [comment] 2024-07-04 20:28
On Manjaro I managed to build it. Currently it's far from being finished, if you can show me some logs of the errors you're facing I can try to help you. I know people that managed to build it on other distros.

> Currently the project requires at least adding in the stb perlin header and changing the std to C99 to be able to build.

If you install stb with your package manager, it should build correctly. (I tried to implement a noise function myself to replace it, but didn't got it working).

I'm doing nearly nothing on this project these last months because I'm writing a full game engine for it, which also simplifies building on multiple platforms (I want to support windows xp and later), but it isn't fully working yet, and I'm coding something else these last times, but I plan to finish it.

Currently you can only explore a terrain. I'm trying to add block breaking...

Thanks for your issue and your interest in this project, I'll try to help you.

Mibi88

**Comment by attilavs2** [comment] 2024-07-06 17:54
Clear dependencies would help with the stb.
The packages i have found for debian are :
`build-essential`
`meson`
`freeglut3-dev` (Doesn't actually work because meson doesn't find it)
`libgl-dev`
`libstb-dev`
`ninja`
I will update this post when i will manage to build it (on Linux Mint 21.3), and add a definitive modification list
Edit : 
Freeglut requires the following to work with debian-based:
```
add_project_link_arguments([
  ´-l:libglut.a',#copied libglut to MibiCraft folder to avoid properly dealing with it 
  '-lX11',  
  '-lXxf86vm',
  '-lXi',  
], language: 'c')
```  

The additional libs should be installed by default.

**Comment by mibi88** [comment] 2024-08-22 17:26
Yes, but when setting the flags manually, meson can't check if the dependencies are available. The issue is that freeglut doesn't provide cmake or pkgconfig files IIRC.

**Comment by attilavs2** [comment] 2024-08-24 07:55
You will know soon enough if you don't actually have the dependencies installed i think.
 Anyways i tried using the "proper way" but since freeglut doesn't provide the package config tools correctly on Debian, i am about left with that (And even if the other dependencies may have "cleaner" ways to link i couldn't be bothered)

**Comment by mibi88** [comment] 2024-08-24 11:12
Yes, I know. But I think that Cmake couldn't handle it any better... I haven't coded on my engine since some time, I should really continue, it is nearly finished, it uses Xlib directly instead of freeglut.

**Comment by mibi88** [comment] 2024-08-24 11:13
I'll close this issue, because it's specific to some distros.

**Closed as completed** 2024-08-24 11:13 UTC
Labels: enhancement
